elasticsearch:
  host: https://127.0.0.1:9200
  username: elastic
  password: elastic
  ssl: true
  ca_certs: /Users/kent/github/connectors-python-main/http_ca.crt
  bulk:
    queue_max_size: 1024
    queue_max_mem_size: 25
    display_every: 100
    chunk_size: 1000
    max_concurrency: 5
    chunk_max_mem_size: 5
    concurrent_downloads: 10
  request_timeout: 120
  max_wait_duration: 120
  initial_backoff_duration: 1
  backoff_multiplier: 2
  log_level: info
  language_code: en
  analysis_icu: false

service:
  idling: 30
  heartbeat: 300
  max_errors: 20
  max_errors_span: 600
  trace_mem: false
  log_level: INFO
  max_concurrent_content_syncs: 10
  max_concurrent_access_control_syncs: 10


connectors:
  -
      connector_id: "jdWY14kBjcZbv3QK5vkY"
      service_type: sncmdb

            
sources:
  mongodb: connectors.sources.mongo:MongoDataSource
  s3: connectors.sources.s3:S3DataSource
  dir: connectors.sources.directory:DirectoryDataSource
  mysql: connectors.sources.mysql:MySqlDataSource
  network_drive: connectors.sources.network_drive:NASDataSource
  google_cloud_storage: connectors.sources.google_cloud_storage:GoogleCloudStorageDataSource
  google_drive: connectors.sources.google_drive:GoogleDriveDataSource
  azure_blob_storage: connectors.sources.azure_blob_storage:AzureBlobStorageDataSource
  postgresql: connectors.sources.postgresql:PostgreSQLDataSource
  oracle: connectors.sources.oracle:OracleDataSource
  sharepoint_server: connectors.sources.sharepoint_server:SharepointServerDataSource
  mssql: connectors.sources.mssql:MSSQLDataSource
  jira: connectors.sources.jira:JiraDataSource
  confluence: connectors.sources.confluence:ConfluenceDataSource
  dropbox: connectors.sources.dropbox:DropboxDataSource
  servicenow: connectors.sources.servicenow:ServiceNowDataSource
  sharepoint_online: connectors.sources.sharepoint_online:SharepointOnlineDataSource
  github: connectors.sources.github:GitHubDataSource
  sncmdb: connectors.sources.sncmdb:SncmdbDataSource
